name: App Release With Docker to Heroku

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push and Release to Heroku
        uses: patrickkkim/heroku-docker-deploy@v1.1
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          options: "--no-cache"
          process_type: web
          db_host: ${{ secrets.DATABASE_HOST }}
          db_name: ${{ secrets.DATABASE_NAME }}
          db_username: ${{ secrets.DATABASE_USERNAME }}
          db_password: ${{ secrets.DATABASE_PASSWORD }}
          fs_api_key: ${{ secrets.FS_API_KEY }}