name: App Release With Docker to Heroku

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push and Release to Heroku
        uses: patrickkkim/docker-compose-multiple-apps-heroku-deploy@v1.1
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          docker_compose_file: "./docker/docker-compose.yml"
          heroku_apps: '[{"imagename":"mysql:8.0","appname":"ruleonewebsite","apptype":"worker"},{"imagename":"ruleone-backend","appname":"ruleonewebsite","apptype":"web"}]'
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_ROOT_PASSWORD: ${{ secrets.DATABASE_ROOT_PASSWORD }}
          FS_API_KEY: ${{ secrets.FS_API_KEY }}